version: '3.7'

services:
  demo-wordpress:
    image: wordpress
   
    environment:
      WORDPRESS_DB_HOST: 'demo-mariadb:3306'
      WORDPRESS_DB_PASSWORD: 'Docker123'
   
    ports:
      - 80:80
    networks:
      - demo-internal
      - demo-web

  demo-mariadb:
    image: mariadb
 
    environment:
      MYSQL_ROOT_PASSWORD: 'Docker123'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'Docker123'
  
  
    networks:
      - demo-internal
    volumes:
     - db:/data/db

volumes:
  db:
    

networks:
  demo-internal:
  demo-web:

