version: '3.7'

services:
  app:
    image: wordpress
   
    environment:
      WORDPRESS_DB_HOST: 'mariadb:3306'
      WORDPRESS_DB_PASSWORD: 'Docker123'
   
    ports:
      - 80-83:80
    networks:
      - internal
      - web

  mariadb:
    image: mariadb
 
    environment:
      MYSQL_ROOT_PASSWORD: 'Docker123'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'Docker123'
  
  
    networks:
      - internal
    volumes:
     - db:/data/db

volumes:
  db:
    

networks:
  internal:
  web:

