version: "3.7"
services:
  monpostgres:
    image: postgres
    #ports
    networks:
      - internal
    volumes:
      - db:/var/lib/postgressql
    environment:
      - POSTGRES_PASSWORD=dockertest

  monadminer:
    image: adminer
    ports:
      - 80:8080
    environment:
      - ADMINER_DEFAULT_SERVER=monpostgres
    networks:
      - internal
      - web

  webpage:
    build: ../webpage-example
    ports:
      - 8584:80
    networks: 
      - web

networks:
  web:
  internal:

volumes:
  db:



# Je veux postgres 11.2
# Je veux une interface d'administration pour postgres (Adminer) configuré pour se connecter sur mon service postgres (ADMINER_DEFAULT_SERVER)
#Je veux deux networks, un qui est réservé aux databases, et un qui est réservé aux acces depuis le web
#je veux que mes deux containers puissent communiquer
#je veux configurer postgres avec son user "postgres" par défaut, et le mot de passe Docker101 (POSTGRES_PASSWORD)

  

