version: "3.7"
services:
  postgres:
    image: postgres:11.2
    #ports:
    networks:
      - internal
    volumes:
      - ./data:/var/lib/postgressql 
    environment:
      - POSTGRES_PASSWORD=Docker101

  adminer:
    image: adminer:latest
    ports: 
      - 8080:8080
    environment: 
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - web
      - internal 
  
  webpage:
    build: ../webpage-example
    command:  bash -c "sed -i 's/React App/Docker/g' /usr/share/nginx/html/index.html && nginx -g \"daemon off;\""
    networks:
      - web
    ports:
      - 8001:80
    

networks:
  internal:
  web: