
version: "3.7"
services:
  training-presentation:
    image: training_docker:2
    deploy:
     
      labels:

        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:training.julien.tech"
        - "traefik.backend=training"
        - "traefik.port=80"
        - "traefik.frontend.entryPoints=http,https"
     
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    external: true

